### PR TITLE
unicode support

### PR DESCRIPTION
**Pull request by BotStop**
Hi. i changed word match.

1. Added 'u' flag to regex.

2. Removed '\b' from regex. Is there any reason for it? Did i miss some cases?

### CODE REVIEW

**Comment by lejara** [comment]
heya @BotStop! Thanks for taking interest in this project! 🙌 

There are no words that require Unicode to be on. So, i would love to understand your reasons to add this

For `/b` being there, to be honest i do not remember the edge case 😄 . It was a year ago when i added it in [this commit.](https://github.com/lejara/Da-Twitch-Charades/commit/8f1a8b97d4f6c462b1adc992896dbb4a309fde48)
Probably something with capturing words with whitespaces in between; this could be wrong.
For now i would like to keep in there, until there is a necessity for its removal.

**Comment by BotStop** [comment]
@lejara 
It's for custom words section. 
Some streamer asked to do this. 
(He tested my fork yesterday and will use on stream later, maybe he will find edge case for `\b`)

Sadly `\b` doesn't work with unicode.  
I checked change history of regex, i think, in the commit accurate of match increased due to last `\b` 
(later, last `\b` were replaced by `(\s|$)`).

**Comment by lejara** [comment]
I do like the idea for support of non-Latin characters for custom words.

i tested your fork, everything behaves as expected.
for the `\b` you are right, it does not catch unicode chars; so lets remove that.

**Review by lejara — CHANGES_REQUESTED** [review]

**Comment by lejara** [comment]
Awesome!

ill go ahead and push it to the pages branch soon

**Pull request merged**
