### PR TITLE
Enabled-only BTTV/FFZ emotes mode

### PR DESCRIPTION
**Pull request by hroland**
Hey! Love this little app you built! So much fun to see Nmp, Malena, XQC, Mizzy and others play it :)

It was sometimes annoying to see chat go `??????` when the game chose an emote thats not enabled on the channel. I saw the game was open source, so I added a few lines to dynamically fetch channel-specific FFZ and BTTV emotes when starting a game (connecting to a chat).

I hope this will make the next version :) Let me know if you'd like something changed or if there's anything else I can help with 💜

[xqcL](https://www.youtube.com/watch?v=xelnFtBUy1w)

(P.s. in your free time check out [Bootstrap](https://www.youtube.com/watch?v=7g8Gg2QVdeU): a popular CSS framework, [Flexbox](https://www.youtube.com/watch?v=JJSoEo8JSnc): built-in CSS layout system, [Vue](https://www.youtube.com/watch?v=Wy9q22isx3U) or [React](https://www.youtube.com/watch?v=sBws8MSXN7A): more modern reactive alternatives to JQuery)

### CODE REVIEW

**Comment by lejara** [comment]
nice work,
While i do want to add this to the project. The problem is the HTML and CSS of this project are generated using [wysiwygwebbuilder](https://www.wysiwygwebbuilder.com/). Mostly Because I wanted to tried it out.

So, the current state of your commits, will cause problems when I build using wysiwygwebbuilder.

At the same time there will always be people in chat who would not know the emote even if its enable in channel. So adding this will not stop chat going "????" for emotes. But I do seeing it might mitigate the issue, emphasis on might.

So its up you to whether or not you would like to fix this. The binary is called TS.wbs that is what wysiwygwebbuilder uses.

**Comment by hroland** [comment]
Interesting choice. I updated the wbs file with wysiwygwebbuilder 15.3. Might be my computer only, but exporting the page made some font larger (13pt to 16pt), even though it looks fine in the editor. Please take a look :)

**Comment by lejara** [comment]
okay quite of few things

1. The font size did change, you are going to need to fix that back

2. In your commit their too many unnecessary marked file changes, that have no changes. You are going to need to remove that.

3. You renamed the existing  BTTV / FFZ Emotes category, you need to change that back
-Also rename your new category to Channel Specific FFZ/BBTV

4. For now, have your new cat unchecked by default, and change back the default settings

5. Make sure the game does not break if the FFZ and BBTV api requests cannot be made  

Also....
-Maybe in the future we can add onto this category, and allow their sub emotes to be in the list too

**Comment by lejara** [comment]
5. also there is conflicting files, mostly because of the little fix i did yesterday. Fix that too. Don't worry i will try not to merge any new edits for those files

**Comment by lejara** [comment]
Forgot to mention, this one of reasons as to why i am not going use  wysiwygwebbuilder in the future

But anyways, 
when it builds the html files for some reason it adds a "return false;" at the end of a event value. And having this prevents the checkboxes from being checked.

So you need to remove it, a simple search and replace should do the job

Example,
Before: <input type="checkbox" id="Super_Hero_Swtich" onclick="p.call(this);return false;" .....
After: <input type="checkbox" id="Super_Hero_Swtich" onclick="p.call(this);" .....

**Comment by lejara** [comment]
Hey man,
Wanna know if this still being worked on. You have 24hours to let me know. Going to be applying a couple of merges soon after.

**Comment by hroland** [comment]
Sorry, I'm caught up with work, and I'm not too comfortable with wbs.

I'd love to see this happen, so I'm down to put the FFZ/BBTV fetcher and mapper functions in a separate file, and have you integrate it, otherwise feel free to close this.

**Comment by lejara** [comment]
All good, 

As I don't see this as a priority I probably will add this in a later version.
Since the main bits are in the "TCharadesGame.js" I can just look back at this pull request when i do get around adding this.

Anyways,
Thank you taking interest in this Project <3
Maybe in the future i will do a rewrite on the HTML/CSS, and add all those sweet stuff

Going to close this now

**Pull request closed without merging**
