### PR TITLE
Added possibility to get emotes from BTTV or FFZ channels

### PR DESCRIPTION
**Pull request by karl-police**
Added possibility to get emotes from BTTV or FFZ channels, at the Custom Words list

HOWEVER, it's not finished yet completly, what you can curretly do, is choose BTTV and insert this in the channel textfield 123217703, reason for that I didn't finish it, is because we need OAuth and if we don't have that we can't do that. But the functions work, there's none for FFZ yet though.

Also, I couldn't make the OAuth thing, because that's something lejara has to setup because it's basically used for the entire page then.

So if you go to Custom Words, you will see a new button.

I was wondering if I can contact lejara about that maybe. I also didn't add error messages, however the stuff for the error messages is already there, just without style and script.

It is currently testable here https://karl-police.github.io/Da-Twitch-Charades/

also add back CNAME, I had to remove that while I was testing

### CODE REVIEW

**Comment by lejara** [comment]
### Okay, some pull request problems

- For the CNAME you should add that back before you do the pull request, you can undo that commit


- Another thing is to add your code in the [TCharadesGame.js](https://github.com/lejara/Da-Twitch-Charades/blob/master/TCharadesGame.js) not the minified version. The minified version is generated using an npm script. (i should have removed the min from the master branch mb)


**For using npm**

- You can also use the npm scripts as well to make the min version. Commands for them are in the [package.json](https://github.com/lejara/Da-Twitch-Charades/blob/master/package.json)

- The one you are looking for is the `uglify:tcg
`
- Make sure to run `npm install` first before you run any of the scripts

### Now onto the OAuth Problem....

1. Now, i am not sure if FFZ and BBTV changed their access to the their api, but there was a person before you that was able to get the data you need without requiring OAuth. Link to his pull request [here](https://github.com/lejara/Da-Twitch-Charades/pull/45)

That pull request could not be merge, because the website at that time was harder to be work on by other people. This is fix now with the rework I did.

2. You can correct if i am wrong, its been a while since i looked into it....... But ideally I do not want to add OAuth. Mainly because I do not want user logging into their accounts before using the website.

3. Lastly, I cannot do much coding on this project right now. As i am too busy on my work.

**Comment by karl-police** [comment]
> ### Okay, some pull request problems
> * For the CNAME you should add that back before you do the pull request, you can undo that commit
> * Another thing is to add your code in the [TCharadesGame.js](https://github.com/lejara/Da-Twitch-Charades/blob/master/TCharadesGame.js) not the minified version. The minified version is generated using an npm script. (i should have removed the min from the master branch mb)
> 
> **For using npm**
> 
> * You can also use the npm scripts as well to make the min version. Commands for them are in the [package.json](https://github.com/lejara/Da-Twitch-Charades/blob/master/package.json)
> * The one you are looking for is the `uglify:tcg `
> * Make sure to run `npm install` first before you run any of the scripts
> 
> ### Now onto the OAuth Problem....
> 1. Now, i am not sure if FFZ and BBTV changed their access to the their api, but there was a person before you that was able to get the data you need without requiring OAuth. Link to his pull request [here](https://github.com/lejara/Da-Twitch-Charades/pull/45)
> 
> That pull request could not be merge, because the website at that time was harder to be work on by other people. This is fixed now with the rework I did.
> 
> 1. You can correct if i am wrong, its been a while since i looked into it....... But ideally I do not want to add OAuth. Mainly because I do not want user logging into their accounts before using the website.
> 2. Lastly, I cannot do much coding on this project right now. As i am too busy on my work.
> 
> **Also thank you for taking interest into this project!** 🥳

OAuth is needed, Twitch changed that. Unless he got the broadcaster id from another API but yeah.

**Comment by karl-police** [comment]
also do you mind adding me on Discord, please?

karl-police#3660

**Comment by karl-police** [comment]
BTTV and FFZ is now supported without OAuth needed, it all uses TwitchJS and the "chat" method
now since the "chat" is also used by the game itsself to detect who finds out the emote. "roundIsActive" has been added to check whetever or not a round is active to use the API, because if you join a chat, you'll be in two chats and other issue is that I also use chat.disconnect to then disconnect from that one chat.

NextGame will check if "isConnected" is false and if it is, it will reconnect to the chat, so yeah.


This can be pushed already, well once I removed it from testing and stuff and added CNAME back. In the future I'll make the channel input only one HTML and use display none and block to hide it, if it is not needed.

**Comment by lejara** [comment]
ill have a proper look at this some other time. I am just too busy with other things right now, sorry

**Comment by karl-police** [comment]
Alright

**Comment by lejara** [comment]
Hey karl-police! Sorry it has been awhile.

So i have been looking into adding this and there's couple of things I wanna talk about.....

### Initial Testing
So I had a look at your changes, also tired to test it with no avail. I Click on the Get Emotes for the BBTV and i get 404 in the console.
But its no big deal because there are I few changes i want to make

### Pull Request Changes
- I noticed you are requesting to merge to `gh-pages` branch. I want you to change that to the `master` branch for the next pull request.
- Also squash your commits into one

So your going to need to make a new pull request

But before that.......

### Wanted Code Changes

I want to move the Import of BTTV and FFZ options away from the custom words model to its own categories, and also use the existing channel name input field instead of another one.

But since this is different to normal static categories, I want to make its own section in the options panel called "Dynamic Categories" (name is still WIP). And the user can only turn it on once the game has started, so its guaranteed we have the channel name to do our requests. Also it is so the user only type in the channel name once.

I was thinking I could add the new option section, and the code for the new categories, and all you need to add is your fetch code of the emotes

Or 

If you okay with it I could take snips of your existing code and add it myself

**Comment by karl-police** [comment]
Well, when it comes to "move pull request branches", it's like an entire mess. It needs one file conflicting somehow so that everything breaks.

But you can use pieces of my existing code sure.

**Comment by karl-police** [comment]
Test it now again.

**Comment by lejara** [comment]
then yeah, it will be better if I take pieces of your existing code and add it myself. And ill add you as a contributor to it, of course!

ill have another look at your changes, but it would be best for you to place your changes on the non-minified version only

**Comment by lejara** [comment]
Also how I tested your changes was by recreating the minified version with your changes

**Comment by lejara** [comment]
Tested your changes works on my end! 🥳

Just have the changes on the `TCharadesGame.js`  and then ill get to work on adding it

**Comment by lejara** [comment]
#80

**Pull request closed without merging**
